### ISSUE TITLE
Locales

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-experiment#30]
How are we going to do the equivalent of https://github.com/mdn/stumptown-experiment/tree/master/content/html/elements/video in French? 

Also, apart from the `title` almost all of the stuff in https://github.com/mdn/stumptown-experiment/blob/master/content/html/elements/video/meta.yaml is "locale agnostic". 

We could get fancy and add `https://github.com/mdn/stumptown-experiment/tree/master/content/html/elements/video/fr/` which would contain `attributes/`, `examples/`, `contributors.md`, `prose.md`. And lastly, it could contain a `meta.yaml` file that is everything that `../meta.yaml` is but with the French "extras". E.g.

```yaml
title: '<video>: L'élément vidéo intégré'
mdn-url: https://developer.mozilla.org/fr/docs/Web/HTML/Element/video
tags:
    group: Image et multimédia
```
